//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _10023767_P2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        public int StudyID { get; set; }
        public Nullable<System.DateTime> DayWorked { get; set; }
        public Nullable<int> WeekWorked { get; set; }
        public Nullable<int> TimeWorked_Hours { get; set; }
        public Nullable<int> TimeWorked_Minutes { get; set; }
        public Nullable<int> ModuleID { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
